package net.riley.riley_mod.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.AbstractCookingRecipe;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.crafting.conditions.IConditionBuilder;
import net.riley.riley_mod.RileyMod;
import net.riley.riley_mod.block.RileyModBlocks;
import net.riley.riley_mod.item.RileyModItems;

import java.util.List;
import java.util.function.Consumer;

public class RileyModRecipeProvider extends RecipeProvider implements IConditionBuilder {
    private static final List<ItemLike> ARMOR_PLATE_SMELTABLES = List.of(Items.IRON_INGOT);
    public RileyModRecipeProvider(PackOutput pOutput) {
        super(pOutput);
    }


    @Override
    protected void buildRecipes(Consumer<FinishedRecipe> pWriter) {
        oreSmelting(pWriter, ARMOR_PLATE_SMELTABLES, RecipeCategory.MISC,
                RileyModItems.ARMOR_PLATING.get(),
                0.7F, 200,
                "armor_plating");
        oreBlasting(pWriter, ARMOR_PLATE_SMELTABLES, RecipeCategory.MISC,
                RileyModItems.ARMOR_PLATING.get(),
                0.7F, 100,
                "armor_plating");
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.CABLE.get(),8)
                .pattern("AAA")
                .pattern("ABA")
                .pattern("AAA")
                .define('A', Items.IRON_NUGGET)
                .define('B',RileyModItems.LIVING_MACHANICAL_NURONS.get())
                        .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.MACHINE_CORE_PORT.get(),4)
                .pattern("BAB")
                .pattern("A A")
                .pattern("BAB")
                .define('A', RileyModBlocks.CABLE.get())
                .define('B',RileyModBlocks.MACHINE_CORE.get())
                .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.MACHINE_CORE_SCREEN.get(),4)
                .pattern(" A ")
                .pattern("ABA")
                .pattern(" A ")
                .define('B', Blocks.GLASS)
                .define('A',RileyModBlocks.MACHINE_CORE.get())
                .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.MACHINE_CORE_CENTER.get())
                .pattern("AAA")
                .pattern("AAA")
                .pattern("AAA")
                .define('A',RileyModBlocks.MACHINE_CORE.get())
                .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.MACHINE_CORE.get(),1)
                .pattern("AA")
                .pattern("AA")
                .define('A',RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.TRISON_CART_COVER.get())
                        .pattern("AAA")
                        .pattern("AAA")
                        .pattern("AAA")
                .define('A', Blocks.WHITE_WOOL)
                .unlockedBy("has_item", has(Blocks.WHITE_WOOL))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.WHEEL.get(), 4)
                        .pattern(" A ")
                        .pattern("ABA")
                        .pattern(" A ")
                .define('A', RileyModBlocks.ABYSS_PLANKS.get())
                .define('B', Blocks.IRON_BLOCK)
                .unlockedBy("has_item", has(RileyModBlocks.ABYSS_PLANKS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.UNASSEMBLED_TRISON_CART.get())
                .pattern("BAB")
                .pattern("AAA")
                .pattern("AAA")
                .define('A', RileyModBlocks.ABYSS_PLANKS.get())
                .define('B', Blocks.CHEST)
                .unlockedBy("has_item", has(RileyModBlocks.ABYSS_PLANKS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.SOUL_FORGE.get())
                .pattern("AAA")
                .pattern("ABA")
                .pattern("AAA")
                .define('A', Blocks.OBSIDIAN)
                .define('B', Items.SOUL_CAMPFIRE)
                .unlockedBy("has_item", has(RileyModBlocks.ABYSS_PLANKS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.LAMP_HOOK.get())
                .pattern(" A ")
                .pattern("B A")
                .pattern("  A")
                .define('A', Items.IRON_INGOT)
                .define('B', Items.LANTERN)
                .unlockedBy("has_item", has(RileyModBlocks.ABYSS_PLANKS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.SOUL_ORB.get())
                .pattern(" A ")
                .pattern("ABA")
                .pattern(" A ")
                .define('A', RileyModItems.FUNTIUM_PLATE.get())
                .define('B', Items.SOUL_LANTERN)
                .unlockedBy("has_item", has(RileyModItems.FUNTIUM_PLATE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.TRISON_CART_ITEM.get())
                .pattern("DCD")
                .pattern("BAE")
                .pattern("BBB")
                .define('A', RileyModItems.UNASSEMBLED_TRISON_CART.get())
                .define('B', RileyModItems.WHEEL.get())
                .define('C', RileyModItems.SOUL_FORGE.get())
                .define('D', RileyModItems.LAMP_HOOK.get())
                .define('E', RileyModItems.TRISON_CART_COVER.get())
                .unlockedBy("has_item", has(RileyModBlocks.ABYSS_PLANKS.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.FALLOW_PORTAL_FRAME.get())
                .pattern("ABA")
                .pattern("BBB")
                .pattern("ABA")
                .define('A', Blocks.SMOOTH_STONE)
                .define('B', Blocks.NETHERRACK)

                .unlockedBy("has_item", has(Blocks.NETHERRACK))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.AUGMENTATION_STATION.get())
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .define('B', Blocks.IRON_BLOCK)
                .define('C', Blocks.RED_STAINED_GLASS_PANE)

                .unlockedBy("has_item", has(RileyModItems.LIVING_MACHANICAL_NURONS.get()))
                .save(pWriter);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.ARTIFICIAL_ORGAN.get())
                .pattern(" BA")
                .pattern("BAB")
                .pattern("AB ")
                .define('A', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .define('B', RileyModItems.SYNTHETIC_MUSCLE.get())

                .unlockedBy("has_item", has(RileyModBlocks.AUGMENTATION_STATION.get()))
                .save(pWriter);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_EGG.get())
                .pattern("EAE")
                .pattern("DBD")
                .pattern("ECE")
                .define('A', RileyModItems.MECHAREX_HEAD.get())
                .define('B', RileyModItems.MECHAREX_TORSO.get())
                .define('C', RileyModItems.MECHAREX_TAIL.get())
                .define('D', RileyModItems.MECHAREX_LEG.get())
                .define('E', RileyModItems.ARMOR_PLATING.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_HEAD.get())
                .pattern("DDD")
                .pattern("DEA")
                .pattern("BBC")
                .define('A', RileyModItems.MECHA_REX_UNASSEMBLED_HEAD.get())
                .define('B', RileyModItems.LYDAR.get())
                .define('C', RileyModItems.MECHAREX_BRAIN.get())
                .define('D', RileyModItems.CANNON_SHEILD.get())
                .define('E', RileyModItems.MECHAREX_CANNON.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_TORSO.get())
                .pattern("CCC")
                .pattern("ABA")
                .pattern("AAA")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .define('B', RileyModItems.UNASSEMBLED_MECHAREX_TORSO.get())
                .define('C', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_TAIL.get())
                .pattern("CCB")
                .pattern("BDC")
                .pattern("BBB")
                .define('B', RileyModItems.SYNTHETIC_MUSCLE.get())
                .define('C', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .define('D', RileyModItems.UNASSEMBLED_MECHAREX_TAIL.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_LEG.get())
                .pattern("BBC")
                .pattern("BAC")
                .pattern("BBB")
                .define('A', RileyModItems.UNASSEMBLED_MECHAREX_LEG.get())
                .define('B', RileyModItems.SYNTHETIC_MUSCLE.get())
                .define('C', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.UNASSEMBLED_MECHAREX_TORSO.get())
                .pattern("AAA")
                .pattern("BCC")
                .pattern("AAA")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .define('B', RileyModItems.MECHAREX_ENGINE.get())
                .define('C', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.UNASSEMBLED_MECHAREX_TAIL.get())
                .pattern("AA ")
                .pattern(" AA")
                .pattern("  A")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.UNASSEMBLED_MECHAREX_LEG.get())
                .pattern("AAA")
                .pattern(" AA")
                .pattern("AAA")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHA_REX_UNASSEMBLED_HEAD.get())
                .pattern("AAA")
                .pattern("A A")
                .pattern("AAA")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.CANNON_SHEILD.get())
                .pattern("AAA")
                .pattern("A  ")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_CANNON.get())
                .pattern("A A")
                .pattern("A A")
                .pattern("BBB")
                .define('A', RileyModItems.ARMOR_PLATING.get())
                .define('B', Items.IRON_BLOCK)
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.LYDAR.get())
                .pattern("BBB")
                .pattern("BAB")
                .pattern("BBB")
                .define('A', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .define('B', Items.RED_STAINED_GLASS_PANE)
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_BRAIN.get())
                .pattern("AAA")
                .pattern(" A ")
                .pattern(" A ")
                .define('A', RileyModItems.LIVING_MACHANICAL_NURONS.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.SYNTHETIC_MUSCLE.get())
                .pattern("AA ")
                .pattern(" AA")
                .pattern("AA ")
                .define('A', Items.SCULK)
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.LIVING_MACHANICAL_NURONS.get(),6)
                .pattern("BBB")
                .pattern("BBB")
                .pattern("AC ")
                .define('B',  ItemTags.create(new ResourceLocation("riley_mod", "meat")))
                .define('A', Items.GLASS_BOTTLE)
                .define('C', Items.CLOCK)
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.SOUL.get(),1)
                .pattern("BBB")
                .pattern("BAB")
                .pattern("BBB")
                .define('B', RileyModItems.ICE_CHUNK.get())
                .define('A', ItemTags.create(new ResourceLocation("riley_mod", "souls")))
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_CREEPER.get(),1)
                        .pattern("ABA")
                        .pattern("BCB")
                        .pattern("ABA")
                        .define('A', Items.GLASS_BOTTLE)
                        .define('B', Blocks.STONE)
                        .define('C', RileyModItems.CREEPER_SOUL.get())
                        .unlockedBy("has_item", has(RileyModItems.CREEPER_SOUL.get()))
                        .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_BAT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.BAT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.BAT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ALLAY.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ALLAY_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ALLAY_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_AXOLOTL.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.AXOLOTL_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.AXOLOTL_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_BEE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.BEE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.BEE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_BLAZE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.BLAZE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.BLAZE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_CAT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.CAT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.CAT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_CAMEL.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.CAMEL_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.CAMEL_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_CAVE_SPIDER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.CAVE_SPIDER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.CAVE_SPIDER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_CHICKEN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.CHICKEN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.CHICKEN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_COD.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.COD_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.COD_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_COW.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.COW_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.COW_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_DOLPHIN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.DOLPHIN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.DOLPHIN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_DONKEY.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.DONKEY_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.DONKEY_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_DROWNED.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.DROWNED_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.DROWNED_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ELDER_GUARDIAN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ELDER_GUARDIAN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ELDER_GUARDIAN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ENDERMAN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ENDERMAN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ENDERMAN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ENDERMITE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ENDERMITE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ENDERMITE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_EVOKER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.EVOKER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.EVOKER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_FOX.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.FOX_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.FOX_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_FROG.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.FROG_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.FROG_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_GHAST.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.GHAST_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.GHAST_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_GLOW_SQUID.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.GLOW_SQUID_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.GLOW_SQUID_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_GOAT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.GOAT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.GOAT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_GUARDIAN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.GUARDIAN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.GUARDIAN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_HOGLIN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.HOGLIN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.HOGLIN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_HORSE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.HORSE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.HORSE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_HUSK.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.HUSK_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.HUSK_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_IRON_GOLEM.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.IRON_GOLEM_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.IRON_GOLEM_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_LLAMA.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.LLAMA_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.LLAMA_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_MAGMA_CUBE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.MAGMA_CUBE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.MAGMA_CUBE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_MOOSHROOM.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.MOOSHROOM_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.MOOSHROOM_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_MULE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.MULE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.MULE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_OCELOT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.OCELOT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.OCELOT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PANDA.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PANDA_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PANDA_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PARROT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PARROT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PARROT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PHANTOM.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PHANTOM_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PHANTOM_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PIG.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PIG_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PIG_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PIGLIN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PIGLIN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PIGLIN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PIGLIN_BRUTE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PIGLIN_BRUTE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PIGLIN_BRUTE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PILLAGER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PILLAGER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PILLAGER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_POLAR_BEAR.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.POLAR_BEAR_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.POLAR_BEAR_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_PUFFERFISH.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.PUFFERFISH_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.PUFFERFISH_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_RABBIT.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.RABBIT_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.RABBIT_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_RAVAGER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.RAVAGER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.RAVAGER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SALMON.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SALMON_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SALMON_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SHEEP.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SHEEP_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SHEEP_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SHULKER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SHULKER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SHULKER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SILVERFISH.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SILVERFISH_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SILVERFISH_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SKELETON.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SKELETON_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SKELETON_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SKELETON_HORSE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SKELETON_HORSE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SKELETON_HORSE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SLIME.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SLIME_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SLIME_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SNIFFER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SNIFFER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SNIFFER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SNOW_GOLEM.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SNOW_GOLEM_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SNOW_GOLEM_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SPIDER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SPIDER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SPIDER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_SQUID.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.SQUID_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.SQUID_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_STRAY.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.STRAY_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.STRAY_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_STRIDER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.STRIDER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.STRIDER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_TADPOLE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.TADPOLE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.TADPOLE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_TRADER_LLAMA.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.TRADER_LLAMA_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.TRADER_LLAMA_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_TROPICAL_FISH.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.TROPICAL_FISH_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.TROPICAL_FISH_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_TURTLE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.TURTLE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.TURTLE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_VEX.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.VEX_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.VEX_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_VILLAGER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.VILLAGER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.VILLAGER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_VINDICATOR.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.VINDICATOR_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.VINDICATOR_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WANDERING_TRADER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WANDERING_TRADER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WANDERING_TRADER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WARDEN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WARDEN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WARDEN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WITCH.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WITCH_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WITCH_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WITHER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WITHER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WITHER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WITHER_SKELETON.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WITHER_SKELETON_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WITHER_SKELETON_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_WOLF.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.WOLF_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.WOLF_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ZOGLIN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ZOGLIN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ZOGLIN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ZOMBIE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ZOMBIE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ZOMBIE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ZOMBIE_HORSE.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ZOMBIE_HORSE_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ZOMBIE_HORSE_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ZOMBIE_VILLAGER.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ZOMBIE_VILLAGER_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ZOMBIE_VILLAGER_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ZOMBIFIED_PIGLIN.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ZOMBIFIED_PIGLIN_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ZOMBIFIED_PIGLIN_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModBlocks.TROPHY_ENDER_DRAGON.get(),1)
                .pattern("ABA")
                .pattern("BCB")
                .pattern("ABA")
                .define('A', Items.GLASS_BOTTLE)
                .define('B', Blocks.STONE)
                .define('C', RileyModItems.ENDER_DRAGON_SOUL.get())
                .unlockedBy("has_item", has(RileyModItems.ENDER_DRAGON_SOUL.get()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, RileyModItems.MECHAREX_ENGINE.get())
                .pattern("CAC")
                .pattern("ABA")
                .pattern("CAC")
                .define('A', Items.SCULK_CATALYST)
                .define('B', Items.NETHER_STAR)
                .define('C', RileyModItems.CAGGED_FAIRY.get())
                .unlockedBy("has_item", has(RileyModItems.EYE.get()))
                .save(pWriter);

    }

    protected static void oreSmelting(Consumer<FinishedRecipe> pFinishedRecipeConsumer, List<ItemLike> pIngredients, RecipeCategory pCategory, ItemLike pResult, float pExperience, int pCookingTIme, String pGroup) {
        oreCooking(pFinishedRecipeConsumer, RecipeSerializer.SMELTING_RECIPE, pIngredients, pCategory, pResult, pExperience, pCookingTIme, pGroup, "_from_smelting");
    }

    protected static void oreBlasting(Consumer<FinishedRecipe> pFinishedRecipeConsumer, List<ItemLike> pIngredients, RecipeCategory pCategory, ItemLike pResult, float pExperience, int pCookingTime, String pGroup) {
        oreCooking(pFinishedRecipeConsumer, RecipeSerializer.BLASTING_RECIPE, pIngredients, pCategory, pResult, pExperience, pCookingTime, pGroup, "_from_blasting");
    }

    protected static void oreCooking(Consumer<FinishedRecipe> pFinishedRecipeConsumer, RecipeSerializer<? extends AbstractCookingRecipe> pCookingSerializer, List<ItemLike> pIngredients, RecipeCategory pCategory, ItemLike pResult, float pExperience, int pCookingTime, String pGroup, String pRecipeName) {
        for(ItemLike itemlike : pIngredients) {
            SimpleCookingRecipeBuilder.generic(Ingredient.of(itemlike), pCategory, pResult,
                            pExperience, pCookingTime, pCookingSerializer)
                    .group(pGroup).unlockedBy(getHasName(itemlike), has(itemlike))
                    .save(pFinishedRecipeConsumer,  RileyMod.MODID + ":" + getItemName(pResult) + pRecipeName + "_" + getItemName(itemlike));
        }
    }
}